default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: trailing-whitespace
    - id: check-added-large-files
    - id: check-executables-have-shebangs

  - repo: local
    hooks:
    - id: clang-format
      name: clang-format
      entry: clang-format -i
      language: system
      types_or: [c, c++]
      args: ["-style=file"]