repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    - id: trailing-whitespace

      #  - repo: https://github.com/pre-commit/mirrors-cpplint
      #    rev: v1.0.0
      #    hooks:
      #      - id: cpplint
      #
      #  - repo: https://github.com/pre-commit/mirrors-clang-format
      #    rev: v2.0.2
      #    hooks:
      #      - id: clang-format
      #        args: [--style=file,--verbose]
