/**:
  ros__parameters:
    map_topic: "/map"
    map_frame: "map"
    pose_topic: "/pose"

    use_sim_time: true

/ndt:
  ros__parameters:
    # NDT matcher
    epsilon: 0.05
    stepsize: 0.1
    resolution: 3.0
    maxiters: 5
    leafsize: 2.0

    # TF2 buffer size
    tf2_buffer_size: 10

    # Subscriber topics
    scan_topic: "/scan"
    initial_pose_topic: "/initial_pose"

    # Publisher topics
    cloud_topic: "/cloud"
    tf_topic: "/tf"
    path_topic: "/rviz/path"

    # Reference frames
    vehicle_frame: "base_link"
    laser_frame: "os_sensor"

/map_publisher:
  ros__parameters:
    map_file: "/ros2_ws/install/ndt_locator/share/ndt_locator/maps/court_yard_map.pcd"

    map_update_threshold: 20.0
    submap_size_xy: 20.0
    submap_size_z: 10.0
